services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    depends_on:
      - db
    volumes:
      - .:/markr_app
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 